# Dependabot configuration for LLM Context Generator VSCode plugin

version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "codybrom"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major-updates:
        patterns:
          - "*"
        update-types:
          - major
